☁️ chore(automation): Applying changes from upstream repository.

diff --git a/.config/taskfiles/ci/Taskfile.yml b/.config/taskfiles/ci/Taskfile.yml
--- a/.config/taskfiles/ci/Taskfile.yml
+++ b/.config/taskfiles/ci/Taskfile.yml
@@ -31,7 +31,8 @@ tasks:
       start: Pulling latest changes
       success: Successfully pulled latest changes
     cmds:
-      - git pull
+      - cmd: git pull
+        ignore_error: true
       - |
         if [ "$CI_COMMIT_REF_NAME" == 'synchronize' ]; then
           git checkout master
@@ -40,6 +41,8 @@ tasks:
           git checkout "$CI_COMMIT_REF_NAME"
           git pull origin "$CI_COMMIT_REF_NAME"
         fi
+    status:
+      - '[ -n "$NO_GIT_CREDS" ]'
 
   codeclimate:
     deps:
@@ -69,28 +72,32 @@ tasks:
   commit:
     deps:
       - :install:software:git
+    vars:
+      CURR_BRANCH:
+        sh: git rev-parse --abbrev-ref HEAD
     log:
-      error: Encountered error while pushing changes to master
-      start: Bypassing git hooks and pushing changes to master (if there are any changes)
+      error: Encountered error while pushing changes to {{.CURR_BRANCH}}
+      start: Bypassing git hooks and pushing changes to {{.CURR_BRANCH}} (if there are any changes)
     cmds:
       - task: commit:config
       - task: lockfiles:clean
-      - |
-        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
-        git add --all
+      - task --list > /dev/null || (echo "ERROR Invalid Taskfiles!" && exit 1)
+      - git add --all
       - git diff --cached "*"
       - |
         if [[ $(git status --porcelain) ]]; then
-          git commit -m "⤵️ automation(synchronize) Applying changes from upstream repository."
-          git push -q -o ci.skip origin master || FAILED_PUSH=$?
+          git commit -m "☁️ chore(automation): Applying changes from upstream repository."
+          git push -q -o ci.skip origin {{.CURR_BRANCH}} || FAILED_PUSH=$?
           if [ -n "$FAILED_PUSH" ]; then
-            git pull origin master
+            git pull -X theirs origin {{.CURR_BRANCH}}
             task --list &> /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
-            git push --force -q -o ci.skip origin master
+            git add --all
+            git commit -m "☁️ chore(automation): Merging changes from upstream repository with -X theirs."
+            git push --force -q -o ci.skip origin {{.CURR_BRANCH}}
           fi
         fi
     status:
-      - '[ -z "$CI" ]'
+      - '[ -z "$CI" ] || [ -n "$NO_GIT_CREDS" ]'
 
   commit:config:
     deps:
@@ -142,11 +149,12 @@ tasks:
         DEFAULT_BRANCH="$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')";
         git checkout -q "$DEFAULT_BRANCH"; git pull -q origin "$DEFAULT_BRANCH" --ff-only'
     status:
-      - '[ -z "$CI" ]'
+      - '[ -z "$CI" ] || [ -n "$NO_GIT_CREDS" ]'
 
   synchronize:
     deps:
       - commit:config
+    run: once
     log:
       error: Failed to update the `synchronize` branch
       start: Synchronizing the `synchronize` branch with the `master` branch
@@ -164,10 +172,13 @@ tasks:
         fi
       - task: synchronize:gitlab
       - git checkout master
+    status:
+      - '[ -n "$NO_GIT_CREDS" ] || ([ "$FULLY_AUTOMATED_TASKS" != "true" ] && [ -z "$CI" ])'
 
   synchronize:gitlab:
+    run: once
     cmds:
       - curl -s --request POST --form "token=${CI_JOB_TOKEN}" --form ref=master --form "variables[PIPELINE_SOURCE]=$PIPELINE_SOURCE"
         "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"
     status:
-      - '[ -z "$GITLAB_CI" ]'
+      - '[ -z "$GITLAB_CI" ] || [ -n "$NO_GITLAB_SYNCHRONIZE" ]'
diff --git a/.config/taskfiles/install/Taskfile-software.yml b/.config/taskfiles/install/Taskfile-software.yml
--- a/.config/taskfiles/install/Taskfile-software.yml
+++ b/.config/taskfiles/install/Taskfile-software.yml
@@ -22,6 +22,8 @@ tasks:
       - task: install:software
         vars:
           PACKAGE: act
+    status:
+      - type act > /dev/null
 
   allure:
     run: once
@@ -29,6 +31,8 @@ tasks:
       - task: install:software
         vars:
           PACKAGE: allure
+    status:
+      - type allure > /dev/null
 
   ansifilter:
     run: once
@@ -38,6 +42,17 @@ tasks:
       - task: install:software
         vars:
           PACKAGE: ansifilter
+    status:
+      - type ansifilter > /dev/null
+
+  axel:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: axel
+    status:
+      - type axel > /dev/null
 
   brew:
     run: once
@@ -75,9 +90,7 @@ tasks:
             .config/log info 'Attempting to install Homebrew - you may be prompted for your `sudo` password'
             /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
           fi
-          if [ '{{.BODEGA}}' != 'true' ]; then
-            task install:software:exit:notice:reload
-          fi
+          task install:software:exit:notice:reload
         fi
       - task: brew:utils
     status:
@@ -107,9 +120,7 @@ tasks:
           fi
           eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
           ensureSource "$HOME/.profile"
-          if [ '{{.BODEGA}}' != 'true' ]; then
-            task install:software:exit:notice:reload
-          fi
+          task install:software:exit:notice:reload
         fi
     status:
       - type brew &> /dev/null
@@ -139,8 +150,10 @@ tasks:
       - task: install:software
         vars:
           INSTALL_TASK: '{{.TASK}}'
-
           PACKAGE: codeclimate/formulae/codeclimate
+    status:
+      - type codeclimate > /dev/null
+
   common:
     run: once
     log:
@@ -172,15 +185,25 @@ tasks:
       LINUX_FAMILY:
         sh: |
           if [ -f "/etc/debian_version" ]; then
-            echo "debian"
+            echo 'debian'
           elif [ -f "/etc/redhat-release" ]; then
-            echo "redhat"
+            echo 'redhat'
           elif [ -f "/etc/arch-release" ]; then
-            echo "archlinux"
-          else [ -f "/etc/alpine-release" ]; then
-            echo "alpine"
+            echo 'archlinux'
+          elif [ -f "/etc/alpine-release" ]; then
+            echo 'alpine'
+          elif type apk &> /dev/null; then
+            echo 'alpine'
+          elif type apt-get &> /dev/null; then
+            echo 'debian'
+          elif type dnf &> /dev/null || type yum &> /dev/null; then
+            echo 'redhat'
+          elif type pacman &> /dev/null; then
+            echo 'archlinux'
+          elif type yum &> /dev/null; then
+            echo 'redhat'
           else
-            echo "unknown"
+            echo 'unknown'
           fi
     log:
       error: Failed to ensure basic system dependencies are installed
@@ -435,6 +458,8 @@ tasks:
       - task: install:software
         vars:
           PACKAGE: container-structure-test
+    status:
+      - type container-structure-test > /dev/null
 
   coreutils:
     cmds:
@@ -451,6 +476,17 @@ tasks:
       - task: install:software
         vars:
           PACKAGE: dasel
+    status:
+      - type dasel > /dev/null
+
+  deno:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: deno
+    status:
+      - type deno > /dev/null
 
   docker:
     run: once
@@ -467,6 +503,8 @@ tasks:
       - task: install:software
         vars:
           PACKAGE: docker-slim
+    status:
+      - type docker-slim > /dev/null
 
   docker:darwin:
     run: once
@@ -497,7 +535,10 @@ tasks:
     cmds:
       - task: install:software
         vars:
+          BIN_NAME: dockle
           PACKAGE: goodwithtech/r/dockle
+    status:
+      - type dockle > /dev/null
 
   exiftool:
     run: once
@@ -514,14 +555,17 @@ tasks:
   exit:notice:reload:
     cmds:
       - .config/log warn 'Software was installed that requires a terminal session reload'
-      - .config/log info 'Please close and re-open the terminal. Then, re-run the same command to continue.'
-      - exit 1
+      - .config/log warn 'Please close and re-open the terminal. Then, re-run the same command to continue if you face any issues.'
+    status:
+      - '[ -f /.dockerenv ]'
 
   exit:notice:restart:
     cmds:
       - .config/log warn 'Software was installed that requires a system reboot'
       - .config/log info 'Please reboot the system and re-run the same command after rebooting'
       - exit 1
+    status:
+      - '[ -f /.dockerenv ]'
 
   expect:
     run: once
@@ -534,6 +578,16 @@ tasks:
           PACKAGE: expect
     status:
       - type expect > /dev/null
+
+  fury:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          BIN_NAME: fury
+          PACKAGE: gemfury/tap/gemfury
+    status:
+      - type fury > /dev/null
 
   gcc:
     run: once
@@ -586,12 +640,32 @@ tasks:
     status:
       - type git > /dev/null
 
+  git-bug:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: git-bug
+    status:
+      - type git-bug > /dev/null
+
+  git-issue:admin:
+    run: once
+    cmds:
+      - git clone https://github.com/dspinellis/git-issue.git .git-issue
+      - |
+        cd .git-issue
+        sudo make install
+      - rm -rf .git-issue
+
   gitlab-runner:
     run: once
     cmds:
       - task: install:software
         vars:
           PACKAGE: gitlab-runner
+    status:
+      - type gitlab-runner > /dev/null
 
   gitleaks:
     run: once
@@ -599,6 +673,8 @@ tasks:
       - task: install:software
         vars:
           PACKAGE: gitleaks
+    status:
+      - type gitleaks > /dev/null
 
   glab:
     run: once
@@ -606,6 +682,17 @@ tasks:
       - task: install:software
         vars:
           PACKAGE: glab
+    status:
+      - type glab > /dev/null
+
+  glow:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: glow
+    status:
+      - type glow > /dev/null
 
   go:
     run: once
@@ -656,6 +743,11 @@ tasks:
         vars:
           PACKAGE: anchore/grype/grype
 
+  gum:
+    run: once
+    cmds:
+      - task: :install:go:gum
+
   gzip:
     run: once
     cmds:
@@ -667,6 +759,20 @@ tasks:
           PACKAGE: gzip
     status:
       - type gzip > /dev/null
+
+  heroku:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: heroku/brew/heroku
+
+  hey:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: hey
 
   install:software:
     vars:
@@ -709,11 +815,35 @@ tasks:
       - type qemu-system-x86_64 > /dev/null
 
   node:
+    deps:
+      - common
+      - volta
+    run: once
+    cmds:
+      - task: node:install
+    status:
+      - type node &> /dev/null
+
+  node:install:
+    cmds:
+      - |
+        . "$HOME/.profile" &> /dev/null || true
+        volta install node
+
+  openssl:
     run: once
     cmds:
       - task: install:software
         vars:
-          PACKAGE: node
+          PACKAGE: openssl
+
+  p7zip:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          BIN_NAME: 7z
+          PACKAGE: p7zip
 
   packer:
     run: once
@@ -732,6 +862,15 @@ tasks:
           CASK: parallels
     status:
       - '[ "{{OS}}" != "darwin" ] || ! mdfind -name "Parallels Desktop.app" &> /dev/null'
+
+  pinentry:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: pinentry-mac
+    status:
+      - '[ "{{OS}}" != "darwin" ] || [ -f /usr/local/bin/pinentry-mac ]'
 
   pipx:
     tags:
@@ -754,9 +893,35 @@ tasks:
       - pipx ensurepath
 
   pipx:linux:
+    deps:
+      - pipx:linux:brew
+      - pipx:linux:system
+
+  pipx:linux:brew:
     cmds:
+      - brew install pipx
+      - pipx ensurepath
+    status:
+      - '! type brew > /dev/null'
+
+  pipx:linux:system:
+    deps:
+      - python
+    cmds:
+      - task: system
+        vars:
+          PACKAGE: python3-pip
+      - task: system
+        vars:
+          PACKAGE: python3-venv
+      - |
+        if ! type pip3; then
+          python3 -m ensurepip > /dev/null
+        fi
       - python3 -m pip install --user pipx
       - python3 -m pipx ensurepath
+    status:
+      - type brew > /dev/null
 
   pipx:windows:
     log:
@@ -795,6 +960,8 @@ tasks:
       - exit 1
 
   python:
+    deps:
+      - common
     run: once
     cmds:
       - task: brew
@@ -819,6 +986,56 @@ tasks:
           PACKAGE: python@3.10
     status:
       - type python3 > /dev/null
+
+  python:pip:
+    run: once
+    cmds:
+      - |
+        PIP_LOCATION="$(which pip)"
+        PIP3_LOCATION="$(which pip3)"
+        if [ "$USER" == "root" ]; then
+          if type pip &> /dev/null && type pip3 &> /dev/null; then
+            rm "$PIP_LOCATION"
+            ln -s "$PIP3_LOCATION" "$PIP_LOCATION"
+          elif type pip3 &> /dev/null; then
+            ln -s "$PIP3_LOCATION" /usr/bin/pip
+          elif type pip &> /dev/null; then
+            ln -s "$PIP_LOCATION" /usr/bin/pip3
+          else
+            .config/log warn 'Both `pip` and `pip3` appear to be missing'
+          fi
+        elif type sudo &> /dev/null && sudo -n true; then
+          if type pip &> /dev/null && type pip3 &> /dev/null; then
+            sudo rm "$PIP_LOCATION"
+            sudo ln -s "$PIP3_LOCATION" "$PIP_LOCATION"
+          elif type pip3 &> /dev/null; then
+            sudo ln -s "$PIP3_LOCATION" /usr/bin/pip
+          elif type pip &> /dev/null; then
+            sudo ln -s "$PIP_LOCATION" /usr/bin/pip3
+          else
+            .config/log warn 'Both `pip` and `pip3` appear to be missing'
+          fi
+        elif type sudo &> /dev/null; then
+          if type pip &> /dev/null && type pip3 &> /dev/null; then
+            .config/log info 'Running `sudo rm $(which pip)`'
+            sudo rm "$PIP_LOCATION"
+            sudo ln -s "$PIP3_LOCATION" "$PIP_LOCATION"
+          elif type pip3 &> /dev/null; then
+            .config/log info 'Running `sudo ln -s $(which pip3) /usr/bin/pip`'
+            sudo ln -s "$PIP3_LOCATION" /usr/bin/pip
+          elif type pip &> /dev/null; then
+            .config/log info 'Running `sudo ln -s $(which pip) /usr/bin/pip3`'
+            sudo ln -s "$PIP_LOCATION" /usr/bin/pip3
+          else
+            .config/log warn 'Both `pip` and `pip3` appear to be missing'
+          fi
+        else
+           .config/log warn '`sudo` unavailable and user has no permissions'
+        fi
+    status:
+      - which pip > /dev/null
+      - which pip3 > /dev/null
+      - '[ "$(which pip)" == "$(which pip3)" ]'
 
   python:windows:
     log:
@@ -848,6 +1065,14 @@ tasks:
           BIN_NAME: cargo
           PACKAGE: rust
 
+  s5cmd:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          BIN_NAME: s5cmd
+          PACKAGE: peak/tap/s5cmd
+
   sentry:
     cmds:
       - task: :install:github:sentry
@@ -857,9 +1082,22 @@ tasks:
     tags:
       - semantic
     cmds:
+      - task: snapcraft:snap
       - task: install:software
         vars:
           PACKAGE: snapcraft
+    status:
+      - type snapcraft > /dev/null
+
+  snapcraft:snap:
+    log:
+      error: Failed to run `sudo snap install snapcraft --classic`
+      start: Running `sudo snap install snapcraft --classic`
+      success: Successfully installed `snapcraft`
+    cmds:
+      - sudo snap install snapcraft --classic
+    status:
+      - '! type snap > /dev/null'
 
   sshfs:
     run: once
@@ -886,28 +1124,41 @@ tasks:
 
   system:
     vars:
-      PACKAGE: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}{{.PACKAGE}}{{end}}'
-    log:
-      error: Failed to install `{{.PACKAGE}}` with the system package manager
-      start: Attempting to install `{{.PACKAGE}}` using the system package manager
+      PACKAGE: '{{if .PACKAGE}}{{.PACKAGE}}{{else}}{{.CLI_ARGS}}{{end}}'
     cmds:
-      - task: system:apk
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:apt-get
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:dnf
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:yum
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:macos
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
+      - .config/log start 'Attempting to install `{{.PACKAGE}}` using the system package manager'
+      - |
+        if [ -f "/etc/redhat-release" ]; then
+          if type dnf &> /dev/null; then
+            task install:software:system:dnf -- '{{.PACKAGE}}'
+          else
+            task install:software:system:yum -- '{{.PACKAGE}}'
+          fi
+        elif [ -f "/etc/debian_version" ]; then
+          task install:software:system:apt-get -- '{{.PACKAGE}}'
+        elif [ -f "/etc/arch-release" ]; then
+          task install:software:system:pacman -- '{{.PACKAGE}}'
+        elif [ -f "/etc/alpine-release" ]; then
+          task install:software:system:apk -- '{{.PACKAGE}}'
+        elif type dnf &> /dev/null; then
+          task install:software:system:dnf -- '{{.PACKAGE}}'
+        elif type yum &> /dev/null; then
+          task install:software:system:yum -- '{{.PACKAGE}}'
+        elif type apt-get &> /dev/null; then
+          task install:software:system:apt-get -- '{{.PACKAGE}}'
+        elif type pacman &> /dev/null; then
+          task install:software:system:pacman -- '{{.PACKAGE}}'
+        elif type apk &> /dev/null; then
+          task install:software:system:apk -- '{{.PACKAGE}}'
+        else
+          if [ '{{OS}}' == 'darwin' ]; then
+            task install:software:system:macos -- '{{.PACKAGE}}'
+          else
+            .config/log error 'No matching system. Cannot continue with installation.' && exit 1
+          fi
+        fi
     status:
-      - type {{.PACKAGE}} > /dev/null
+      - type {{.PACKAGE}} > /dev/null || [ '{{.PACKAGE}}' == 'null' ]
 
   system:apk:
     vars:
@@ -1025,6 +1276,14 @@ tasks:
         vars:
           PACKAGE: aquasecurity/trivy/trivy
 
+  unbuffer:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          BIN_NAME: unbuffer
+          PACKAGE: expect
+
   vagrant:
     cmds:
       - task: vagrant:{{OS}}
@@ -1071,7 +1330,7 @@ tasks:
       - task: vmware:{{OS}}
       - task: exit:notice:restart
     status:
-      - type vmware > /dev/null
+      - type vmrun > /dev/null
 
   vmware:darwin:
     run: once
@@ -1086,6 +1345,18 @@ tasks:
       - task: :install:install-doctor
         vars:
           SOFTWARE: vmware
+
+  volta:
+    run: once
+    cmds:
+      - .config/log info 'Installing Volta'
+      - curl https://get.volta.sh | bash
+      - |
+        . "$HOME/.profile" &> /dev/null || true
+        volta setup
+      - .config/log success 'Successfully setup Volta'
+    status:
+      - type volta > /dev/null
 
   yarn:
     tags:
@@ -1104,3 +1375,10 @@ tasks:
       - task: install:software
         vars:
           PACKAGE: yq
+
+  yubikey-agent:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: yubikey-agent
diff --git a/.config/taskfiles/lint/Taskfile.yml b/.config/taskfiles/lint/Taskfile.yml
--- a/.config/taskfiles/lint/Taskfile.yml
+++ b/.config/taskfiles/lint/Taskfile.yml
@@ -42,7 +42,9 @@ tasks:
       start: Linting project with Ansible Lint
       success: Validated project with Ansible Lint
     cmds:
-      - '{{.PYTHON_HANDLE}}ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}'
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}
 
   any:
     deps:
@@ -53,11 +55,13 @@ tasks:
       error: Errors were reported by the global linters for `{{.CLI_ARGS}}`
       start: Linting `{{.CLI_ARGS}}` with global linters
     cmds:
-      - '{{.PYTHON_HANDLE}}blocklint --wordlist blacklist,slave,whitelist {{.CLI_ARGS}}'
-      - '{{.PYTHON_HANDLE}}check-merge-conflict {{.CLI_ARGS}}'
-      - '{{.PYTHON_HANDLE}}check-added-large-files {{.CLI_ARGS}}'
-      - '{{.PYTHON_HANDLE}}check-symlinks {{.CLI_ARGS}}'
-      - '{{.PYTHON_HANDLE}}destroyed-symlinks {{.CLI_ARGS}}'
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        blocklint --wordlist blacklist,slave,whitelist {{.CLI_ARGS}}
+      - PATH="$PATH:$HOME/.local/bin" && check-merge-conflict {{.CLI_ARGS}}
+      - PATH="$PATH:$HOME/.local/bin" && check-added-large-files {{.CLI_ARGS}}
+      - PATH="$PATH:$HOME/.local/bin" && check-symlinks {{.CLI_ARGS}}
+      - PATH="$PATH:$HOME/.local/bin" && destroyed-symlinks {{.CLI_ARGS}}
 
   codeclimate:
     deps:
@@ -91,7 +95,17 @@ tasks:
       start: Running `codeclimate`
       success: Successfully validated the project by running `codeclimate`
     cmds:
-      - CODECLIMATE_DEBUG=1 codeclimate analyze --dev{{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
+      - |
+        if [ -z "$CODECLIMATE_INTEGRATION_TEST" ]; then
+          CODECLIMATE_DEBUG=1 codeclimate analyze --dev{{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
+        else
+          while read PATHH; do
+            cd "$(dirname $PATHH)" && break
+          done < <(find test -maxdepth 2 -type f -name .codeclimate.yml)
+          task lint:codeclimate:taskfiles:add
+          CODECLIMATE_DEBUG=1 codeclimate analyze --dev
+          task lint:codeclimate:taskfiles:remove
+        fi
 
   commit:
     deps:
@@ -115,7 +129,7 @@ tasks:
           TMP="$(mktemp)"
           COMMIT_MSG_NOEMOJI="$(sed 's/^..//' < '{{.CLI_ARGS}}' | xargs)"
           .config/log info 'Linting commit message (with emoji stripped)'
-          echo "$COMMIT_MSG_NOEMOJI" | {{.NPX_HANDLE}}commitlint || (mv '{{.CLI_ARGS}}.bak' '{{.CLI_ARGS}}' && exit 1)
+          echo "$COMMIT_MSG_NOEMOJI" | commitlint || (mv '{{.CLI_ARGS}}.bak' '{{.CLI_ARGS}}' && exit 1)
         elif [ '{{.CLI_ARGS}}' == '.git/MERGE_MSG' ]; then
           .config/log info 'Bypassing commitlint since the message is a merge message'
         fi
@@ -168,11 +182,11 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
-          docker run -v "$PWD:/work" -w /work megabytelabs/hadolint:slim {{.CLI_ARGS | replace .PWD ""}}
+          docker run -v "$PWD:/work" -w /work megabytelabs/hadolint:slim -c .config/hadolint.yml {{.CLI_ARGS | replace .PWD ""}}
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name Dockerfile -o \
             -name Dockerfile.j2 \) -print0 | xargs -0 -r -n1 docker run -v "$PWD:/work" -w /work \
-            megabytelabs/hadolint:slim
+            megabytelabs/hadolint:slim -c .config/hadolint.yml
         {{end}}
 
   dockerfile:
@@ -224,7 +238,7 @@ tasks:
       success: Successfully passed the ESLint test (please still address warnings)
     cmds:
       - >
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
         --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   eslint:staged:
@@ -240,7 +254,7 @@ tasks:
       success: Successfully linted modified files with ESLint
     cmds:
       - >
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
         --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   eslint:warn-all:
@@ -261,7 +275,7 @@ tasks:
       - >
         ESLINT_TMP="$(mktemp)"
 
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format summary --cache
+        eslint -c package.json --no-eslintrc --format summary --cache
         --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} |
         tee "$ESLINT_TMP"
 
@@ -308,7 +322,7 @@ tasks:
       success: Successfully passed ESLint checks for {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}JavaScript/TypeScript files{{end}}
     cmds:
       - >
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --ext .js,.jsx,.ts,.tsx --cache
+        eslint -c package.json --no-eslintrc --format pretty --ext .js,.jsx,.ts,.tsx --cache
         --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   lint-staged:
@@ -320,7 +334,13 @@ tasks:
       start: Linting staged files
       success: The staged files appear to be good!
     cmds:
-      - '{{.NPX_HANDLE}}lint-staged'
+      - |
+        lint-staged || LINT_EXIT_CODE="$?"
+        if [ -n "$LINT_EXIT_CODE" ]; then
+          .config/log error 'Linting failed!'
+          .config/log info 'If necessary, you can bypass this pre-commit hook by running `git commit --no-verify`. Please try to fix the errors first.'
+          exit 1
+        fi
 
   packer:
     deps:
@@ -398,15 +418,16 @@ tasks:
       success: Prettier successfully finished
     cmds:
       - |
-        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+        prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
         if [ -n "$EXIT_CODE" ]; then
-          .config/log warn 'Failed to lint with `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
+          .config/log warn 'Failed to lint with `prettier` - falling back to `prettier`'
           prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
         fi
 
   python:
     deps:
-      - :install:pipx:flake8
+      - python:deps:flake8
+      - python:deps:python
     label: lint:python
     desc: Lint Python files using Flake8
     hide: '{{ne .REPOSITORY_TYPE "python"}}'
@@ -432,17 +453,32 @@ tasks:
       `task lint:python -- myfile.py`
 
       For more information, see [Flake8's GitHub page](https://github.com/PyCQA/flake8).
+    vars:
+      CONFIG_COMMAND:
+        sh: |
+          if [ -f {{.FLAKE8_CONFIG}} ]; then
+            echo '--config {{.FLAKE8_CONFIG}} '
+          fi
     log:
       error: flake8 detected some issues
       start: Linting {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}the project{{end}} with flake8
       success: flake8 validation was successful
     cmds:
       - |
-        {{if .CLI_ARGS}}
-          {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} {{.CLI_ARGS}}
-        {{else}}
-          {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} .
-        {{end}}
+        PATH="$PATH:$HOME/.local/bin"
+        flake8 {{.CONFIG_COMMAND}}{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+
+  python:deps:flake8:
+    cmds:
+      - task: :install:pipx:flake8
+    status:
+      - '[ "{{.REPOSITORY_TYPE}}" == "python" ]'
+
+  python:deps:python:
+    cmds:
+      - task: :install:python:requirements
+    status:
+      - '[ "{{.REPOSITORY_TYPE}}" != "python" ]'
 
   shell:
     cmds:
@@ -479,10 +515,10 @@ tasks:
       - |
         .config/log info 'Linting with Shellcheck'
         {{if .CLI_ARGS}}
-          {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} {{.CLI_ARGS}}
+          shellcheck -e {{.SHELLCHECK_EXCLUDE}} {{.CLI_ARGS}}
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) \
-          -print0 | xargs -0 -r -n1 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}}
+          -print0 | xargs -0 -r -n1 shellcheck -e {{.SHELLCHECK_EXCLUDE}}
         {{end}}
 
   spelling:
@@ -516,7 +552,7 @@ tasks:
       - cmd: |
           set -e
           EXIT_CODE=0
-          {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}} || EXIT_CODE=$?
+          cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}} || EXIT_CODE=$?
           if [ "$EXIT_CODE" != '0' ]; then
             .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
           fi
@@ -554,7 +590,7 @@ tasks:
             EXIT_CODE=0
             .config/log info 'Running a spell-check on staged files with `cspell`'
             # Must not quote $STAGED_FILES
-            {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} $STAGED_FILES || EXIT_CODE=$?
+            cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} $STAGED_FILES || EXIT_CODE=$?
             if [ "$EXIT_CODE" != '0' ]; then
               .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
             fi
@@ -580,7 +616,9 @@ tasks:
       start: Ensuring {{if .CLI_ARGS}}`{{.CLI_ARGS}}` is valid TOML{{else}}the project'\''s TOML files are valid{{end}}
       success: The TOML appears to be valid!
     cmds:
-      - '{{.PYTHON_HANDLE}}check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   vagrant:
     deps:
@@ -622,7 +660,9 @@ tasks:
       start: Ensuring {{if .CLI_ARGS}}{{.CLI_ARGS}} is valid XML{{else}}the project contains only valid XML{{end}}
       success: The XML appears to be valid
     cmds:
-      - '{{.PYTHON_HANDLE}}check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   yaml:
     deps:
@@ -653,4 +693,6 @@ tasks:
       start: Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with `yamllint`
       success: No issues were detected by `yamllint`
     cmds:
-      - '{{.PYTHON_HANDLE}}yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
